### ISSUE TITLE
Undefined property: Xiaolin\Blade\Engines\CompilerEngine::$session

### ISSUE THREAD

**Issue by robertsanseries** [XiaoLer/blade#13]
Problems working with sessions in codeigniter.

A PHP Error was encountered

Severity: Notice

Message: Undefined property: Xiaoler\Blade\Engines\CompilerEngine::$session

Filename: cache/877d4256ca2b11e0616b3866aa1e54f6

**Comment by xleliu** [comment]
CompilerEngine does not has this property.

**Comment by Iyongbudiarso** [comment]
Hey @robertsanseries 
Check my anwser on this link

https://github.com/cntaoyu/CI-Blade/issues/3

**Comment by robertsanseries** [comment]
@Iyongbudiarso Many thanks, I'll test the solution: D
