### ISSUE TITLE
Fatal error: require(): Failed opening required '../src/helpers.php'

### ISSUE THREAD

**Issue by clytras** [XiaoLer/blade#16]
I get a fatal error when I'm trying to use the example code. Am I doing something wrong?

> Warning: require(../src/helpers.php): failed to open stream: No such file or directory in /vendor/xiaoler/blade/src/Autoloader.php on line 12
> 
> Warning: require(../src/helpers.php): failed to open stream: No such file or directory in /vendor/xiaoler/blade/src/Autoloader.php on line 12
> 
> Fatal error: require(): Failed opening required '../src/helpers.php' (include_path='.:/opt/php56/lib/php') in /vendor/xiaoler/blade/src/Autoloader.php on line 12

**EDIT**

Just changed `require '../src/helpers.php';` to `require 'helpers.php';` inside the `Autoloader.php` and it's now working. Why do I get this error? I just C/P the sample code and created a simple view. Also why does the include use `../src/` for `helpers.php`, a file that it's inside the same directory with the `Autoloader.php`?

**Comment by xleliu** [comment]
It just because I have a folder named 'test' for test code 😄

**Comment by clytras** [comment]
You should consider fixing this issue, because now I have removed `xiaoler/blade` from my `composer.json` because if you release a new version and I do a `composer update`, then my code will break again.
