### ISSUE TITLE
Fatal error with undefined method last when using components

### ISSUE THREAD

**Issue by clytras** [XiaoLer/blade#17]
Inside `\Concerns\ManagesComponents.php` at [line 109](https://github.com/XiaoLer/blade/blob/5.4/src/Concerns/ManagesComponents.php#L109) the line has `last($this->componentStack);` which should be `Arr::last($this->componentStack);` and use the static class at the top `use Xiaoler\Blade\Support\Arr;`.

**Comment by xleliu** [comment]
fixed.

**Comment by clytras** [comment]
Same problem here `\Engines\CompilerEngine.php` [line 91](https://github.com/XiaoLer/blade/blob/5.4/src/Engines/CompilerEngine.php#L90).

**Comment by xleliu** [comment]
OK, fixed it.
