### ISSUE TITLE
Error while registering autoloader

### ISSUE THREAD

**Issue by vanrez-nez** [XiaoLer/blade#19]
Hello, Im trying to do a basic render but after requiring the autoload.php and doing

`Xiaoler\Blade\Autoloader::register();`

I'm getting the following error:

( ! ) Warning: require(./helpers.php): failed to open stream: No such file or directory in /var/www/html/some-path/vendor/xiaoler/blade/src/Autoloader.php on line 12

the line responsible inside Autoloader is:
`require './helpers.php';`

presumably because the  ./

**Comment by xleliu** [comment]
fixed

**Comment by an-amin** [comment]
> fixed

I am still facing the error!
