### ISSUE TITLE
你好, 请教一个关于laravel的 DB 基本用法迁移的问题

### ISSUE THREAD

**Issue by fizzcome** [XiaoLer/blade#2]
如这里所说: http://stackoverflow.com/questions/27956821/can-i-use-dbtabletags-outside-of-laravel  
网上有很多教程移植 `Eloquent` , 并且可以使用成功, 如移植到 codeigniter 中, 可以直接使用 Active Record 用法(User::first());  
可是, 如何移植他的基本用法呢 ? 如: DB::table('user')->get();

**Comment by xleliu** [comment]
你发的链接里一楼的答案不就是吗？
