### ISSUE TITLE
Argument 1 passed to Xiaoler\Blade\Compilers\Compiler::__construct() 

### ISSUE THREAD

**Issue by marcuxyz** [XiaoLer/blade#20]
Hi guys,

An uncaught Exception was encountered

Type: TypeError

Message: Argument 1 passed to Xiaoler\Blade\Compilers\Compiler::__construct() must be an instance of Xiaoler\Blade\Filesystem, string given, called in C:\xampp\htdocs\application\libraries\Blade.php on line 18

Filename: C:\xampp\htdocs\vendor\xiaoler\blade\src\Compilers\Compiler.php

Line Number: 33

Backtrace:

File: C:\xampp\htdocs\application\libraries\Blade.php
Line: 18
Function: __construct

File: C:\xampp\htdocs\index.php
Line: 315
Function: require_once

**Comment by hury88** [comment]
I have the same problem with you。
`https://github.com/XiaoLer/blade/wiki`
There are indeed some problems

`https://github.com/XiaoLer/blade`
The code on this page is the perfect solution
