### ISSUE TITLE
Undefined offset: 3

### ISSUE THREAD

**Issue by Excas** [XiaoLer/blade#5]
protected function compileStatements($value)
{
    $callback = function ($match) {
        if (strpos($match[1], '@') !== false) {
            $match[0] = isset($match[3]) ? $match[1].$match[3] : $match[1];
        } elseif (isset($this->customDirectives[$match[1]])) {
            $match[0] = call_user_func($this->customDirectives[$match[1]], ($match[3] ?: ''));
        } elseif (method_exists($this, $method = 'compile'.ucfirst($match[1]))) {
            $match[0] = $this->$method(($match[3] ?: ''));
        }

```
    return isset($match[3]) ? $match[0] : $match[0].$match[2];
};

return preg_replace_callback('/\B@(@?\w+)([ \t]*)(\( ( (?>[^()]+) | (?3) )* \))?/x', $callback, $value);
```

}
xiaoler\blade\src\Compilers\BladeCompiler.php 248 line

**Comment by xleliu** [comment]
好的 我尽快看一下

**Comment by xleliu** [comment]
@Excas fixed

**Comment by Excas** [comment]
给力！！
